apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-connector-deploy
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      volumes:
      - name: mongodb-connector
        configMap:
          name: mongodb-connector
      containers:
      - name: mongodb-connector-deploy
        image: cnfldemos/alpine-curl:3.10.2_7.65.1
        args: [
          "-s",
          "-X", "POST",
          "-H", "Content-Type: application/json",
          "--data", "@/etc/config/connector/mongodb-connector.json",
          "http://connect:8083/connectors"
        ]
        volumeMounts:
          - name: mongodb-connector
            mountPath: /etc/config/connector
      restartPolicy: Never
  backoffLimit: 1